OPTIONS (SKIP=1, ERRORS=0)
LOAD DATA
CHARACTERSET AL32UTF8
APPEND
INTO TABLE autor
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  autor_id INTEGER EXTERNAL,
  ime CHAR,
  prezime CHAR,
  godina_rodjenja INTEGER EXTERNAL,
  drzava CHAR
)
