OPTIONS (SKIP=1, ERRORS=0)
LOAD DATA
CHARACTERSET AL32UTF8
APPEND
INTO TABLE biblioteka
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  biblioteka_id INTEGER EXTERNAL,
  naziv CHAR,
  adresa CHAR,
  grad_id INTEGER EXTERNAL
)
