OPTIONS (SKIP=1, ERRORS=0)
LOAD DATA
CHARACTERSET AL32UTF8
APPEND
INTO TABLE clan
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  clan_id INTEGER EXTERNAL,
  ime CHAR,
  prezime CHAR,
  pol CHAR,
  datum_rodjenja DATE "YYYY-MM-DD",
  email CHAR,
  datum_uclanjenja DATE "YYYY-MM-DD"
)
