OPTIONS (SKIP=1, ERRORS=0)
LOAD DATA
CHARACTERSET AL32UTF8
APPEND
INTO TABLE izdavac
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  izdavac_id INTEGER EXTERNAL,
  naziv CHAR,
  drzava CHAR
)
