OPTIONS (SKIP=1, ERRORS=0)
LOAD DATA
CHARACTERSET AL32UTF8
APPEND
INTO TABLE odeljenje
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  odeljenje_id INTEGER EXTERNAL,
  naziv CHAR,
  biblioteka_id INTEGER EXTERNAL
)
