OPTIONS (SKIP=1, ERRORS=0)
LOAD DATA
CHARACTERSET AL32UTF8
APPEND
INTO TABLE pozajmica
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  pozajmica_id INTEGER EXTERNAL,
  datum_pozajmice DATE "YYYY-MM-DD",
  rok_vracanja DATE "YYYY-MM-DD",
  datum_vracanja DATE "YYYY-MM-DD",
  clan_id INTEGER EXTERNAL,
  primerak_id INTEGER EXTERNAL,
  status_pozajmice_id INTEGER EXTERNAL
)
