OPTIONS (SKIP=1, ERRORS=0)
LOAD DATA
CHARACTERSET AL32UTF8
APPEND
INTO TABLE publikacija
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  publikacija_id INTEGER EXTERNAL,
  naslov CHAR(1000),
  isbn CHAR,
  godina_izdanja INTEGER EXTERNAL,
  broj_strana INTEGER EXTERNAL,
  tip_publikacije_id INTEGER EXTERNAL,
  izdavac_id INTEGER EXTERNAL
)
